# Generated by Django 4.0.3 on 2022-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0004_alter_profile_user_profile_password_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='password_store',
            name='key',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
