# Generated by Django 4.0.3 on 2022-07-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0005_password_store_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password_store',
            name='key',
        ),
    ]
